AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for the SNS subscription.

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/
      Runtime: python3.12
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MySNSTopic
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref MySNSTopic
